src/java/model/Superviseur.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author salatou
 */
@Entity
@Table(name = "superviseur", catalog = "grh_projetjee", schema = "")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Superviseur.findAll", query = "SELECT s FROM Superviseur s")
    , @NamedQuery(name = "Superviseur.findByIdentifiant", query = "SELECT s FROM Superviseur s WHERE s.identifiant = :identifiant")})
public class Superviseur implements Serializable {

    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "prenom")
    private String prenom;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "nom")
    private String nom;
    @Column(name = "datenaissance")
    @Temporal(TemporalType.DATE)
    private Date datenaissance;
    // @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", message="Invalid email")//if the field contains email address consider using this annotation to enforce field validation
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "email")
    private String email;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "password")
    private String password;
    @Basic(optional = false)
    @NotNull
    @Lob
    @Size(min = 1, max = 65535)
    @Column(name = "adresse")
    private String adresse;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "telephone")
    private String telephone;

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "identifiant", nullable = false, length = 255)
    private String identifiant;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "superviseur")
    private Collection<Note> noteCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "superviseur")
    private Collection<Employe> employeCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "superviseur")
    private Collection<Personnel> personnelCollection;
    @JoinColumn(name = "departement", referencedColumnName = "identifiant", nullable = false)
    @ManyToOne(optional = false)
    private Departement departement;

    public Superviseur() {
    }

    public Superviseur(String identifiant) {
        this.identifiant = identifiant;
    }

    public String getIdentifiant() {
        return identifiant;
    }

    public void setIdentifiant(String identifiant) {
        this.identifiant = identifiant;
    }

    @XmlTransient
    public Collection<Note> getNoteCollection() {
        return noteCollection;
    }

    public void setNoteCollection(Collection<Note> noteCollection) {
        this.noteCollection = noteCollection;
    }

    @XmlTransient
    public Collection<Employe> getEmployeCollection() {
        return employeCollection;
    }

    public void setEmployeCollection(Collection<Employe> employeCollection) {
        this.employeCollection = employeCollection;
    }

    @XmlTransient
    public Collection<Personnel> getPersonnelCollection() {
        return personnelCollection;
    }

    public void setPersonnelCollection(Collection<Personnel> personnelCollection) {
        this.personnelCollection = personnelCollection;
    }

    public Departement getDepartement() {
        return departement;
    }

    public void setDepartement(Departement departement) {
        this.departement = departement;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (identifiant != null ? identifiant.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Superviseur)) {
            return false;
        }
        Superviseur other = (Superviseur) object;
        if ((this.identifiant == null && other.identifiant != null) || (this.identifiant != null && !this.identifiant.equals(other.identifiant))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "model.Superviseur[ identifiant=" + identifiant + " ]";
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public Date getDatenaissance() {
        return datenaissance;
    }

    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
}

src/java/controller/SuperviseurController.java
package controller;

import model.Superviseur;
import controller.util.JsfUtil;
import controller.util.PaginationHelper;
import session.SuperviseurFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("superviseurController")
@SessionScoped
public class SuperviseurController implements Serializable {

    private Superviseur current;
    private DataModel items = null;
    @EJB
    private session.SuperviseurFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public SuperviseurController() {
    }

    public Superviseur getSelected() {
        if (current == null) {
            current = new Superviseur();
            selectedItemIndex = -1;
        }
        return current;
    }

    private SuperviseurFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Superviseur) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Superviseur();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SuperviseurCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Superviseur) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SuperviseurUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Superviseur) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("SuperviseurDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Superviseur getSuperviseur(java.lang.String id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Superviseur.class)
    public static class SuperviseurControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            SuperviseurController controller = (SuperviseurController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "superviseurController");
            return controller.getSuperviseur(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Superviseur) {
                Superviseur o = (Superviseur) object;
                return getStringKey(o.getIdentifiant());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Superviseur.class.getName());
            }
        }

    }

}

web/superviseur/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateSuperviseurTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_identifiant}" for="identifiant" />
                    <h:inputText id="identifiant" value="#{superviseurController.selected.identifiant}" title="#{bundle.CreateSuperviseurTitle_identifiant}" required="true" requiredMessage="#{bundle.CreateSuperviseurRequiredMessage_identifiant}"/>
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_departement}" for="departement" />
                    <h:selectOneMenu id="departement" value="#{superviseurController.selected.departement}" title="#{bundle.CreateSuperviseurTitle_departement}" required="true" requiredMessage="#{bundle.CreateSuperviseurRequiredMessage_departement}">
                        <f:selectItems value="#{departementController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_prenom}" for="prenom" />
                    <h:inputText id="prenom" value="#{superviseurController.selected.prenom}" title="#{bundle.CreateSuperviseurTitle_prenom}" required="true" requiredMessage="#{bundle.CreateSuperviseurRequiredMessage_prenom}"/>
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_nom}" for="nom" />
                    <h:inputText id="nom" value="#{superviseurController.selected.nom}" title="#{bundle.CreateSuperviseurTitle_nom}" required="true" requiredMessage="#{bundle.CreateSuperviseurRequiredMessage_nom}"/>
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_datenaissance}" for="datenaissance" />
                    <h:inputText id="datenaissance" value="#{superviseurController.selected.datenaissance}" title="#{bundle.CreateSuperviseurTitle_datenaissance}" >
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_email}" for="email" />
                    <h:inputText id="email" value="#{superviseurController.selected.email}" title="#{bundle.CreateSuperviseurTitle_email}" required="true" requiredMessage="#{bundle.CreateSuperviseurRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_password}" for="password" />
                    <h:inputText id="password" value="#{superviseurController.selected.password}" title="#{bundle.CreateSuperviseurTitle_password}" required="true" requiredMessage="#{bundle.CreateSuperviseurRequiredMessage_password}"/>
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_adresse}" for="adresse" />
                    <h:inputTextarea rows="4" cols="30" id="adresse" value="#{superviseurController.selected.adresse}" title="#{bundle.CreateSuperviseurTitle_adresse}" required="true" requiredMessage="#{bundle.CreateSuperviseurRequiredMessage_adresse}"/>
                    <h:outputLabel value="#{bundle.CreateSuperviseurLabel_telephone}" for="telephone" />
                    <h:inputText id="telephone" value="#{superviseurController.selected.telephone}" title="#{bundle.CreateSuperviseurTitle_telephone}" required="true" requiredMessage="#{bundle.CreateSuperviseurRequiredMessage_telephone}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{superviseurController.create}" value="#{bundle.CreateSuperviseurSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{superviseurController.prepareList}" value="#{bundle.CreateSuperviseurShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateSuperviseurIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/superviseur/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditSuperviseurTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_identifiant}" for="identifiant" />
                    <h:inputText id="identifiant" value="#{superviseurController.selected.identifiant}" title="#{bundle.EditSuperviseurTitle_identifiant}" required="true" requiredMessage="#{bundle.EditSuperviseurRequiredMessage_identifiant}"/>
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_departement}" for="departement" />
                    <h:selectOneMenu id="departement" value="#{superviseurController.selected.departement}" title="#{bundle.EditSuperviseurTitle_departement}" required="true" requiredMessage="#{bundle.EditSuperviseurRequiredMessage_departement}">
                        <f:selectItems value="#{departementController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_prenom}" for="prenom" />
                    <h:inputText id="prenom" value="#{superviseurController.selected.prenom}" title="#{bundle.EditSuperviseurTitle_prenom}" required="true" requiredMessage="#{bundle.EditSuperviseurRequiredMessage_prenom}"/>
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_nom}" for="nom" />
                    <h:inputText id="nom" value="#{superviseurController.selected.nom}" title="#{bundle.EditSuperviseurTitle_nom}" required="true" requiredMessage="#{bundle.EditSuperviseurRequiredMessage_nom}"/>
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_datenaissance}" for="datenaissance" />
                    <h:inputText id="datenaissance" value="#{superviseurController.selected.datenaissance}" title="#{bundle.EditSuperviseurTitle_datenaissance}" >
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_email}" for="email" />
                    <h:inputText id="email" value="#{superviseurController.selected.email}" title="#{bundle.EditSuperviseurTitle_email}" required="true" requiredMessage="#{bundle.EditSuperviseurRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_password}" for="password" />
                    <h:inputText id="password" value="#{superviseurController.selected.password}" title="#{bundle.EditSuperviseurTitle_password}" required="true" requiredMessage="#{bundle.EditSuperviseurRequiredMessage_password}"/>
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_adresse}" for="adresse" />
                    <h:inputTextarea rows="4" cols="30" id="adresse" value="#{superviseurController.selected.adresse}" title="#{bundle.EditSuperviseurTitle_adresse}" required="true" requiredMessage="#{bundle.EditSuperviseurRequiredMessage_adresse}"/>
                    <h:outputLabel value="#{bundle.EditSuperviseurLabel_telephone}" for="telephone" />
                    <h:inputText id="telephone" value="#{superviseurController.selected.telephone}" title="#{bundle.EditSuperviseurTitle_telephone}" required="true" requiredMessage="#{bundle.EditSuperviseurRequiredMessage_telephone}"/>
                </h:panelGrid>
                <h:commandLink action="#{superviseurController.update}" value="#{bundle.EditSuperviseurSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditSuperviseurViewLink}"/>
                <br />
                <h:commandLink action="#{superviseurController.prepareList}" value="#{bundle.EditSuperviseurShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditSuperviseurIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/superviseur/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListSuperviseurTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListSuperviseurEmpty}" rendered="#{superviseurController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{superviseurController.items.rowCount > 0}">
                    <h:outputText value="#{superviseurController.pagination.pageFirstItem + 1}..#{superviseurController.pagination.pageLastItem + 1}/#{superviseurController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{superviseurController.previous}" value="#{bundle.Previous} #{superviseurController.pagination.pageSize}" rendered="#{superviseurController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{superviseurController.next}" value="#{bundle.Next} #{superviseurController.pagination.pageSize}" rendered="#{superviseurController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{superviseurController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_identifiant}"/>
                            </f:facet>
                            <h:outputText value="#{item.identifiant}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_departement}"/>
                            </f:facet>
                            <h:outputText value="#{item.departement}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_prenom}"/>
                            </f:facet>
                            <h:outputText value="#{item.prenom}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_nom}"/>
                            </f:facet>
                            <h:outputText value="#{item.nom}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_datenaissance}"/>
                            </f:facet>
                            <h:outputText value="#{item.datenaissance}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_password}"/>
                            </f:facet>
                            <h:outputText value="#{item.password}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_adresse}"/>
                            </f:facet>
                            <h:outputText value="#{item.adresse}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListSuperviseurTitle_telephone}"/>
                            </f:facet>
                            <h:outputText value="#{item.telephone}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{superviseurController.prepareView}" value="#{bundle.ListSuperviseurViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{superviseurController.prepareEdit}" value="#{bundle.ListSuperviseurEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{superviseurController.destroy}" value="#{bundle.ListSuperviseurDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{superviseurController.prepareCreate}" value="#{bundle.ListSuperviseurCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListSuperviseurIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>